match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
# nightly features
comment_width = 120
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
